theme="archie"
baseURL = 'www.hruby.xyz'
locale = 'en-us'
title = '_epsln'
pygmentsstyle = "monokai"
[params]
    color="dark"
	mode="auto"
	useCDN=false
	subtitle = "Welcome to my blog about security research topics and CTFs I find interesting :)"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
